FROM nginx:1.27-alpine AS production

# 安装 htpasswd 工具（用于 Basic Auth）
RUN apk add --no-cache apache2-utils

# 创建 Basic Auth 用户密码文件
# 你可以通过构建参数传入用户名和密码
ARG BASIC_USER=walter
ARG BASIC_PASS=Oracl3123456

RUN mkdir -p /etc/nginx/auth && \
    htpasswd -b -c /etc/nginx/auth/.htpasswd $BASIC_USER $BASIC_PASS

# 删除默认配置
RUN rm /etc/nginx/conf.d/default.conf

# 复制 Nginx 配置
COPY ./nginx.conf /etc/nginx/conf.d/default.conf

# 复制前端构建产物

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]

